Projeto_LASI/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('aplicativo.urls'))
]

aplicativo/urls.py
from django.urls import path
from aplicativo import views

app_name = 'aplicativo'

urlpatterns = [
    path('', views.ProdutoMenu.as_view(), name='menu'),
    path('list', views.ProdutoList.as_view(), name='list'),
    path('create/', views.ProdutoCreate.as_view(), name='create'),
    path('update/<int:pk>/', views.ProdutoUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', views.ProdutoDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ProdutoDelete.as_view(), name='delete'),
]

aplicativo/models.py
from django.db import models


# Create your models here.

class Produto(models.Model):
    nome = models.CharField(max_length=30)
    preco = models.DecimalField(blank=False, null=False, decimal_places=2, max_digits=4)
    estoque = models.IntegerField(blank=False, null=False)

    def __str__(self):
        return self.nome

aplicativo/forms.py
from django import forms

from aplicativo.models import Produto


class ProdutoForms(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'

aplicativo/views.py
from django.urls import reverse_lazy
import django.views.generic
from aplicativo.models import Produto

# Create your views here.

class ProdutoList(django.views.generic.ListView):
    model = Produto
    queryset = Produto.objects.all()


class ProdutoCreate(django.views.generic.CreateView):
    model = Produto
    fields = '__all__'
    success_url = reverse_lazy('aplicativo:list')


class ProdutoUpdate(django.views.generic.UpdateView):
    model = Produto
    fields = '__all__'
    success_url = reverse_lazy('aplicativo:list')


class ProdutoDetail(django.views.generic.DetailView):
    model = Produto
    queryset = Produto.objects.all()


class ProdutoDelete(django.views.generic.DeleteView):
    queryset = Produto.objects.all()
    success_url = reverse_lazy('aplicativo:list')


class ProdutoMenu(django.views.generic.TemplateView):
    template_name = 'menu.html'

templates/aplicativo/produto_confirm_delete.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Apagar</title>
</head>
<body style="background-color: brown; color: white; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;">
<center>
    <h1>Você tem certeza que deseja apagar {{object.nome}}?</h1>
    <form action="." method="post">
        {% csrf_token %}
        <input type="submit" value="Sim, tenho certeza">
        <input type="reset" value="Desejo Voltar" onclick="location.href = '{% url 'aplicativo:menu' %}'">
    </form>
</center>

</body>
</html>

templates/aplicativo/produto_detail.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Detalhamento</title>
</head>
<body style="background-color: brown; color: white; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;">
<center>
    <h1>Detalhes do Produto</h1>
    Nome do Produto: {{object.nome}}
    <br />
    Preço do Produto: {{object.preco}} R$
    <br />
    Estoque do Produto: {{object.estoque}}
    <br />
    <br />
    <input type="submit" value="Deseja deletar o produto?" onclick="location.href = '{% url 'aplicativo:delete' pk=object.id %}'">
    <br />
    <br />
    <input type="submit" value="Deseja editar o produto?" onclick="location.href = '{% url 'aplicativo:update' pk=object.id %}'">
    <br />
    <br />
    <input type="submit" value="Voltar" onclick="location.href = '{% url 'aplicativo:menu' %}'">
    <br />
</center>

</body>
</html>

templates/aplicativo/produto_form.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cadastro</title>
    <style>
    .center {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }
</style>
</head>
<body style="background-color: brown; color: white; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;">
<center>
    <h1>Por favor, cadastre o produto</h1>
    <form method=POST action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Salvar" onclick="location.href = '{% url 'aplicativo:menu' %}'">
        <input type="reset" value="Cancelar" onclick="location.href = '{% url 'aplicativo:menu' %}'">
    </form>
</center>
</body>
</html>

templates/aplicativo/produto_list.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lista de Produtos</title>

</head>
<body style="background-color: brown; color: white; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;">
<center>
    <h1>Lista de Produtos</h1>
    <ul>
        {% for Produto in object_list %}
        <li>{{Produto.nome}} - <a href="{% url 'aplicativo:detail' pk=Produto.id %}">Detalhes</a></li>
        {% endfor %}
    </ul>
    <input type="reset" value="Voltar ao Menu Inicial" onclick="location.href = '{% url 'aplicativo:menu' %}'">
</center>

</body>
</html>

templates/menu.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Menu Inicial</title>
    <style>
    .center {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

</style>
</head>
<body style="background-color: brown; color: white; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px;">
<div class="center">
    <h1>Bem vindo, selecione a opção que deseja:</h1>
    <input type="submit" value="Cadastrar Novo Produto" onclick="location.href = '{% url 'aplicativo:create' %}'">
    <input type="submit" value="Listar Produtos" onclick="location.href = '{% url 'aplicativo:list' %}'">
</div>


</body>
</html>